site_name: TemplatePowerShellModule
site_author: ''
docs_dir: 'md-docs'
site_dir: 'docs'
use_directory_urls: false
theme:
  name: 'readthedocs'
nav:
- Home: 'index.md'
- Generel:
  - 'Verb-Noun': 'Verb-Noun.md'
- About:
  - 'Changelog': 'CHANGELOG.md'
  - 'Contributing': 'CONTRIBUTING.md'